from typing import Protocol


class CloudApiError(Exception):
    pass


class NotLoggedInError(Exception):
    pass


class SyncBackend(Protocol):
    def find_vault_file(self) -> str | None: ...

    def download_vault_file(self, remote_id: str) -> bytes: ...

    def upload_vault_file(self, data: bytes, remote_id: str | None = None) -> str: ...

    def get_remote_modified_time(self, remote_id: str) -> str | None: ...


class OAuthProvider(Protocol):
    def load_config(self) -> bool: ...

    def save_config(self, client_id: str, client_secret: str) -> None: ...

    def run_login_flow(self) -> str: ...

    def is_logged_in(self) -> bool: ...

    def delete_credentials(self) -> None: ...

    def get_display_name(self) -> str: ...

    def get_authenticated_client(self) -> SyncBackend: ...
