[project]
name = "apass"
version = "0.1.0"
description = ""
authors = [
    {name = "Nikita Shmakov",email = "nikshmakov@gmail.com"}
]

requires-python = ">=3.14"
dependencies = [
    "typer>=0.15,<1",
    "google-api-python-client>=2,<3",
    "google-auth>=2,<3",
    "google-auth-oauthlib>=1,<2",
    "yadisk>=3,<4",
    "pykeepass (>=4.1.1.post1,<5.0.0)",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=8,<9",
    "basedpyright (>=1.39.7,<2.0.0)",
]

[project.scripts]
apass = "apass.cli:app"

[tool.poetry]
packages = [{include = "apass", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
